# Generated by Django 4.2 on 2023-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(upload_to='static/quiz_images/', verbose_name='your photo'),
        ),
    ]
